configuration: Release

cache:
  - src/packages -> src/**/packages.config

before_build:
  - nuget restore src\Costura.sln

build:
  parallel: true
  project: src\Costura.sln

test:
  assemblies:
    - src\Costura.Tests\bin\Release\Costura.Tests.dll